In [4]:
import numpy as np

### Creating Array from a list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:", arr_2d)

1D Array: [1 2 3 4 5]

2D Array: [[1 2 3]
 [4 5 6]]


### List vs NumPY Arrays

In [6]:
py_list = [1, 2, 3]
print("Python list multiplication", py_list * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [7]:
np_array = np.array([1, 2, 3]) # Element wise multiplication
print("Python array multiplication", np_array * 2)

Python array multiplication [2 4 6]


In [8]:
import time
start = time.time()
py_list = [i * 2 for i in range(100000)]
print("\nList operation time: ", time.time()-start)


List operation time:  0.02221822738647461


In [9]:
start = time.time()
np_array = np.arange(100000) * 2
print(np_array)
print("\nNumpy operation time: ", time.time()-start)

[     0      2      4 ... 199994 199996 199998]

Numpy operation time:  0.005976676940917969


### Creating array from scratch

In [10]:
zeros = np.zeros((3, 4))
print("Zeros array:\n", zeros)

ones = np.ones((5, 7))
print("\nOnes array:\n", ones)

full = np.full((3, 6), 7)
print("\nFull arrays:\n", full)

random = np.random.random((4, 5))
print("\nRandom arrays:\n", random)

sequence = np.arange(0, 10, 2)
print("\nSequence array:\n", sequence)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

Full arrays:
 [[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]

Random arrays:
 [[0.26062577 0.90201709 0.49006036 0.1618835  0.87457545]
 [0.87433473 0.01660673 0.28740939 0.92939841 0.98107224]
 [0.45089143 0.639067   0.60960677 0.14258948 0.53169509]
 [0.28382526 0.9079093  0.17814432 0.0174279  0.80787572]]

Sequence array:
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [11]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nMatrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("\nTensor:\n", tensor)

Vector:  [1 2 3]

Matrix:  [[1 2 3]
 [4 5 6]]

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [12]:
array_for_properties = np.array([[1, 2, 3],
                                 [4, 5, True]])
print("Shape: ", array_for_properties.shape)
print("Dimention: ", array_for_properties.ndim)
print("Size: ", array_for_properties.size)
print("Datatype: ", array_for_properties.dtype)

Shape:  (2, 3)
Dimention:  2
Size:  6
Datatype:  int64


### Array reshaping

In [13]:
array_for_reshaping = np.arange(12)
print("Original array: ", array_for_reshaping)

reshaped = array_for_reshaping.reshape(3, 4)
print("\nReshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\nFlattened array: ", flattened)

# Ravel: Return view, instead of copy
raveled = reshaped.ravel()
print("\nRaveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("\nTransposed array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
