### Numpy array operations

In [1]:
import numpy as np

### 1D Arrays

In [2]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing: ", array1[2:7])
print("With Step: ", array1[1:8:2])
print("Negative indexing: ", array1[-3])

Basic slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative indexing:  8


### 2D Arrays

In [3]:
array2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element: ", array2[1, 2])
print("Entire row: ", array2[1])
print("Entire column: ", array2[:, 1])


Specific element:  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [4]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array:", np.sort(unsorted))

array_2d_unsorted = np.array([[9, 9],
                              [2, 3],
                              [1, 7]])
print("Sorted 2D array by row: ", np.sort(array_2d_unsorted, axis=0))

Sorted array: [1 1 2 3 4 5 6 9]
Sorted 2D array by row:  [[1 3]
 [2 7]
 [9 9]]


### Filter

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [6]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [8]:
conditional_arrays = np.where(numbers > 5, "true", "false")
print(conditional_arrays)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatiblity

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatiblity shapes", a.shape == b.shape)

Compatiblity shapes True


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_coloumn = np.hstack((original, new_col))
print("With new coloumn:", with_new_coloumn)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new coloumn: [[1 2 7]
 [3 4 8]]


In [12]:
array_delete = np.array([1, 2, 3, 4, 5])
deleted = np.delete(array_delete, 2)
print("Array after deletion", deleted)

Array after deletion [1 2 4 5]
